#!/bin/sh

#- Merge branches quicker with `fzf`

#* git fzf

gitmer () {
  git checkout $target
  git pull
  git checkout $current
  git merge $target
  git status
}

target=$(git branch | fzf)
current=$(git branch --show-current)
[ "$target" = "$source" ] || [ -z "$target" ] || gitmer

